lexik_jwt_authentication:
    secret_key:       '/home/adam/rapowo.pl/backend/config/jwt/private.pem' # required for token creation
    public_key:       '/home/adam/rapowo.pl/backend/config/jwt/public.pem'
    pass_phrase: 'aaaaa5'
