<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiClose\\TextsController::addComment' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\TextsController::addText' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\ApiClose\\TextsController::deleteComment' => ['privates', '.service_locator.oKrcl6Q', 'get_ServiceLocator_OKrcl6QService.php', true],
    'App\\Controller\\ApiClose\\TextsController::editComment' => ['privates', '.service_locator.oKrcl6Q', 'get_ServiceLocator_OKrcl6QService.php', true],
    'App\\Controller\\ApiClose\\TextsController::editText' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\TextsController::removeText' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\TextsController::setCommentRating' => ['privates', '.service_locator.oKrcl6Q', 'get_ServiceLocator_OKrcl6QService.php', true],
    'App\\Controller\\ApiClose\\TextsController::setTextRating' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\UserController::editProfile' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\ApiOpen\\TextsController::getText' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiOpen\\TextsController::getTexts' => ['privates', '.service_locator.aZJMQbn', 'get_ServiceLocator_AZJMQbnService.php', true],
    'App\\Controller\\Security\\SecurityController::activation' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController::checkEmail' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController::checkNick' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController::login' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\Security\\SecurityController::registerUser' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController::sendRegisterMessage' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\ApiClose\\TextsController:addComment' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\TextsController:addText' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\ApiClose\\TextsController:deleteComment' => ['privates', '.service_locator.oKrcl6Q', 'get_ServiceLocator_OKrcl6QService.php', true],
    'App\\Controller\\ApiClose\\TextsController:editComment' => ['privates', '.service_locator.oKrcl6Q', 'get_ServiceLocator_OKrcl6QService.php', true],
    'App\\Controller\\ApiClose\\TextsController:editText' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\TextsController:removeText' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\TextsController:setCommentRating' => ['privates', '.service_locator.oKrcl6Q', 'get_ServiceLocator_OKrcl6QService.php', true],
    'App\\Controller\\ApiClose\\TextsController:setTextRating' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiClose\\UserController:editProfile' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\ApiOpen\\TextsController:getText' => ['privates', '.service_locator.PxdYYhb', 'get_ServiceLocator_PxdYYhbService.php', true],
    'App\\Controller\\ApiOpen\\TextsController:getTexts' => ['privates', '.service_locator.aZJMQbn', 'get_ServiceLocator_AZJMQbnService.php', true],
    'App\\Controller\\Security\\SecurityController:activation' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController:checkEmail' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController:checkNick' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController:login' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\Security\\SecurityController:registerUser' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\Security\\SecurityController:sendRegisterMessage' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
