<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PxdYYhb' shared service.

return $this->privates['.service_locator.PxdYYhb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'texts' => ['privates', '.errored..service_locator.PxdYYhb.App\\Entity\\Texts', NULL, 'Cannot autowire service ".service_locator.PxdYYhb": it references class "App\\Entity\\Texts" but no such service exists.'],
]);
