<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRjwx6i\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRjwx6i/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRjwx6i.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRjwx6i\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXRjwx6i\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XRjwx6i',
    'container.build_id' => '5ab0b398',
    'container.build_time' => 1556618491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRjwx6i');
