<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxhuL7H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxhuL7H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxhuL7H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxhuL7H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUxhuL7H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UxhuL7H',
    'container.build_id' => '9fe9be69',
    'container.build_time' => 1556468089,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxhuL7H');
